title: "Jaja"
description: "Tecnologia, projetos e coisas que estou aprendendo."
url: ""

markdown: kramdown

permalink: /posts/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"