title: "Jamily Labs"
description: "Estudando, criando e anotando coisas sobre tecnologia."

url: "https://milly5ants.github.io"
baseurl: "/mily_labs"

markdown: kramdown

permalink: /posts/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post